theme: jekyll-theme-minimal
title: 'Introduction to Single Cell RNA-Seq Workshop'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_May_2020.pdf
  - title: Experimental Design and Cost Estimation
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/singlecell/scRNAseq-expDesign_May_2020.pdf
  - title: Single Cell Sample Preparation - Dr. Diana Burkart-Waco
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/singlecell/2020_SingleCell_SampleTalk_DBurkart_Aug.pdf
  - title: Biology at True Resolution - Introduction to Single Cell and Visium Spatial Solutions
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/singlecell/10x_Product_Overview_0813_UCD.pdf
  - title: Visium Spatial Protocols - Tissue Preparation Guide
    url: https://support.10xgenomics.com/spatial-gene-expression/sample-prep/doc/demonstrated-protocol-visium-spatial-protocols-tissue-preparation-guide

  - heading: Support
  - title: Using Slack in this workshop
    url: base/slack
  - title: Using Zoom in this workshop
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI - Logging in and Transferring Files
    url: prerequisites/cli/logging-in
  - title: CLI - Intro to Command-Line
    url: prerequisites/cli/command-line-intro
  - title: CLI - Advanced Command-Line (extra)
    url: prerequisites/cli/advanced-command-line
  - title: CLI - Running jobs on the Cluster and using modules
    url: prerequisites/cli/cluster
  - title: R - Getting Started
    url: prerequisites/intro2R/RStudio
  - title: R - Intro to R
    url: prerequisites/intro2R/Intro2R_mm
  - title: R - Prepare Data in R (extra)
    url: prerequisites/intro2R/data_in_R_prepare_fixed
  - title: R - Data in R (extra)
    url: prerequisites/intro2R/data_in_R_fixed
  - title: More Materials (extra)
    url: https://ucdavis-bioinformatics-training.github.io/2019-Winter-Bioinformatics_Command_Line_and_R_Prerequisites_Workshop/

  - heading: Data Reduction
  - title: Project setup
    url: data_reduction/project_setup
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix

  - heading: scRNAseq Analysis
  - title: Prepare scRNAseq Analysis
    url: data_analysis/scrna_analysis_prepare
  - title: scRNAseq Analysis - PART1
    url: data_analysis/scRNA_Workshop-PART1_fixed
  - title: scRNAseq Analysis - PART2
    url: data_analysis/scRNA_Workshop-PART2_fixed
  - title: scRNAseq Analysis - PART3
    url: data_analysis/scRNA_Workshop-PART3_fixed
  - title: scRNAseq Analysis - PART4
    url: data_analysis/scRNA_Workshop-PART4_fixed
  - title: scRNAseq Analysis - PART5
    url: data_analysis/scRNA_Workshop-PART5_fixed
  - title: scRNAseq Analysis - PART6
    url: data_analysis/scRNA_Workshop-PART6_fixed
  - title: Shiny App (extra)
    url: data_analysis/shiny_app_install
  - title: Shiny App on AWS (extra)
    url: data_analysis/shiny_on_aws

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2020-August-intro-scRNAseq
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
