theme: jekyll-theme-minimal
title: 'Metagenomics and Metatranscriptomics'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_Dec_2021.pdf
  - title: Overview
    url: data_analysis/overview

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites

  - heading: Data Analysis
  - title: Files and Filetypes
    url: data_analysis/filetypes
  - title: Prepare dataset
    url: data_analysis/00-project_setup_mm
  - title: Preprocessing raw data
    url: data_analysis/01-preproc_htstream_mm
  - title: Metagenomics data analysis
    url: data_analysis/02-metagenomics

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-December-Metagenomics-and-Metatranscriptomics
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
